-- MySQL Script generated by MySQL Workbench
-- Wed Mar 21 15:40:07 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema userDBBacke-end
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema userDBBacke-end
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userDBBacke-end` DEFAULT CHARACTER SET utf8 ;
USE `userDBBacke-end` ;

-- -----------------------------------------------------
-- Table `userDBBacke-end`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userDBBacke-end`.`user` (
  `id` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `lastName` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
